server:
    port: 8090
spring:
    datasource:
        password: Surya@555
        url: jdbc:mysql://localhost:3306/security?createDatabaseIfNotExist=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect